#!/bin/bash

# Update the lists
sudo apt update


# Add the repository in sources
sourceFile=/etc/apt/sources.list.d/pgdg.list

if [ -f "$sourceFile" ]
then
	echo "You already have PostgreSQL repo in your sources lists"
else
	echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" | sudo tee --append $sourceFile
fi


# Import the repository signing key
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add


# Update the package lists
sudo apt update


# Install the package PostegreSQL
sudo apt install postgresql-11 php php-pgsql -y


# Add space for clear output
echo -e "\n\n"


# Test the installaion and display the version
echo "[INFO] Version installed : "
psql --version


# Start the service and give it status (get port number)
echo "[INFO] Starting the service : "
sudo service postgresql start
service postgresql status


# END
echo "[INFO]  SETUP FINISH"
